version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          env:
            TOKEN: ${{ secrets.AUTHTOKEN }}
          command: |
            echo $TOKEN
